version: '3.9'

services:
  api:
    build:
      context: ./backend/graphQL_api
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - backend-network
    ports:
      - "8000:8000"
    labels:
      - timeweb.port=8000
      - timeweb.protocol=http

  bot:
    build:
      context: ./bot/dobrodel_bot
      dockerfile: Dockerfile
    container_name: bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      API_URL: http://api:8000
    depends_on:
      - api
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
