version: '3.9'

services:
  api:
    build:
      context: ./backend/graphQL_api
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend-network
    ports:
      - "8000:8000"
    labels:
      kompose.service.expose: "8000"

  postgres:
    build:
      context: .
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - backend-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    labels:
      - traefik.enable=false

  bot:
    build:
      context: ./bot/dobrodel_bot
      dockerfile: Dockerfile
    container_name: bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      API_URL: http://api:8000
    depends_on:
      - postgres
      - api
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge